### ISSUE TITLE
encoder in Canon Lens

### ISSUE THREAD

**Issue by tappete** [max-verem/LensRotaryDecoder#1]
Hi, I'm very interested of  this project and I would like to be able to send the encoder data to Arduino but I can't decode the output pulses from a Canon lens (I work in television and I have a lens like yours with Virtual Output).
I can read the data of the classic rotary encoders without any kind of problem but nothing to do for those integrated in the Canon lens, even after having created your circuit and taken the output pulses.
Are the Canon optics encoders different, what is the problem?

Many thanks and I hope you can help me!

Best regards,
Davide

**Comment by max-verem** [comment]
I am not sure if Arduino has enough cpu power to decode sequence from lens. have a look on diagram:

![Untitled](https://github.com/max-verem/LensRotaryDecoder/assets/10303377/e7fe2761-6ee2-47be-a3cc-5d679d0bbf5c)

A/B pulses distance is about 1us.

**Comment by tappete** [comment]
ok, so the output is a quadrature but very fast...

Thank you
